name: Publish LiteIndex
on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish with Gradle
        run: ./gradlew clean build publish
        env:
          ETERNAL_CODE_MAVEN_USERNAME: ${{ secrets.ETERNAL_CODE_MAVEN_USERNAME }}
          ETERNAL_CODE_MAVEN_PASSWORD: ${{ secrets.ETERNAL_CODE_MAVEN_PASSWORD }}
          MINE_CODES_MAVEN_USERNAME: ${{ secrets.MINE_CODES_MAVEN_USERNAME }}
          MINE_CODES_MAVEN_PASSWORD: ${{ secrets.MINE_CODES_MAVEN_PASSWORD }}